station-distance: 7         #Дистанция, на которой нужно находиться игроку относительно станции радиотрансляции, что бы его голос транслировался на радиоприёмники.
                            #Если не знаешь, что поставить - ставь 7.

receiver-distance: 15       #Дистанция, на которой игроки смогут слышать звук из радиоприёмника.
                            #Если не знаешь, что поставить - ставь 15.

bar-color: "BLUE"           #Цвет полосы регулировки волны.
                            #На выбор есть BLUE, RED, GREEN, PINK, PURPLE,WHITE,YELLOW